### ISSUE TITLE
When env proxy is defined, stacktrace is displayed instead of a nice error message

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#218]
I set a proxy in my environment because I need to access github : 
`# export http_proxy=http://my.proxy:3128`

Then I try to use passhport-admin, which should fail (because I don't need proxy to connect to passhportd), but the error message could be nicer : 

```
$ passhport-admin target list
Traceback (most recent call last):
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/urllib3/connection.py", line 294, in connect
    self._tunnel()
  File "/usr/lib64/python3.4/http/client.py", line 857, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='passhport.libit.fr', port=5000): Max retries exceeded with url: /target/list (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/passhport/passhport/passhport-admin/manager/requests_functions.py", line 42, in get
    r = requests.get(url, verify=config.certificate_path)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='passhport.libit.fr', port=5000): Max retries exceeded with url: /target/list (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 488, in <module>
    requests_object_method(options)
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 475, in requests_object_method
    getattr(prompt_functions, method)(obj)
  File "/home/passhport/passhport/passhport-admin/manager/prompt_functions.py", line 22, in list
    return req.list(obj)
  File "/home/passhport/passhport/passhport-admin/manager/requests_functions.py", line 56, in list
    return get(config.url_passhport + obj + "/list")
  File "/home/passhport/passhport/passhport-admin/manager/requests_functions.py", line 44, in get
    print("ERROR: " + str(e.message))
AttributeError: 'ProxyError' object has no attribute 'message'
```

**Comment by elg** [comment]
Correction done. Still I need you to test it again in your configuration (I was unable to reproduce the exact same error).

**Comment by Raphux** [comment]
Yep, perfect.

```
$ passhport-admin target list
ERROR: Connection error. Check your configuration.
HTTPSConnectionPool(host='passhport.jcdecaux.com', port=5000): Max retries exceeded with url: /target/list (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))
$
```

Closing.
