### ISSUE TITLE
Stacktrace when removing a target that's still in a group

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#231]
Create a target and add it to a group : 
```
[root@passhport-dev-centos7 ~]# passhport-admin target create mytarget 127.0.0.1
OK: "mytarget" -> created
[root@passhport-dev-centos7 ~]# passhport-admin targetgroup addtarget mytarget all
OK: "mytarget" added to "all"
[root@passhport-dev-centos7 ~]# 
```
Try to remove the target : 
```
[root@passhport-dev-centos7 ~]# passhport-admin target delete mytarget
Name: mytarget
Hostname: 127.0.0.1
Server Type : ssh
Login: root
Port: 22
SSH options: 
Comment: 
Attached users: 
Usergroup list: 
Users who can access this target: erwan.legall@librit.fr raphael.berlamont@librit.fr
All usergroups: 
Member of the following targetgroups: all
Are you sure you want to delete mytarget? [y/N] y
[
...
]
Traceback (most recent call last):
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/passhport/passhport/passhportd/app/views_mod/target/__init__.py", line 355, in target_delete
    target.Target.name == name).delete()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 3212, in delete
    delete_op.exec_()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1179, in exec_
    self._do_exec()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1363, in _do_exec
    mapper=self.mapper)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "target" violates foreign key constraint "tgroup_target_target_id_fkey" on table "tgroup_target"
DETAIL:  Key (id)=(1659) is still referenced from table "tgroup_target".
 [SQL: 'DELETE FROM target WHERE target.name = %(name_1)s'] [parameters: {'name_1': 'mytarget'}]

-->

[root@passhport-dev-centos7 ~]#
```

**Comment by elg** [comment]
I can't reproduce it. Is the bug still there after updating the code?

**Comment by elg** [comment]
If the bug still exist, it's ceraintly because of the constraints on postgresql vs sqlite. In this case I'll need to check the constraints and test it in a better way before any action on database.

**Comment by Raphux** [comment]
Yep, stacktrace stills there with PostgreSQL backend.

**Comment by elg** [comment]
Work is done for the users. We need to do the same for targets.

**Comment by elg** [comment]
Need some tests.

**Comment by Raphux** [comment]
Still here
```
Traceback (most recent call last):
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/passhport/passhport/passhportd/app/views_mod/target/__init__.py", line 355, in target_delete
    target.Target.name == name).delete()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 3212, in delete
    delete_op.exec_()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1179, in exec_
    self._do_exec()
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1363, in _do_exec
    mapper=self.mapper)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/passhport/passhport-run-env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "target" violates foreign key constraint "tgroup_target_target_id_fkey" on table "tgroup_target"
DETAIL:  Key (id)=(1659) is still referenced from table "tgroup_target".
 [SQL: 'DELETE FROM target WHERE target.name = %(name_1)s'] [parameters: {'name_1': 'mytarget'}]

-->

```

**Comment by Raphux** [comment]
Done by elg in #236
