### ISSUE TITLE
Stack trace when setting PWD_RST_AFTER_SESSION to True

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#242]
When setting PWD_RST_AFTER_SESSION to "True" in /etc/passhport/passhport.ini, I got this when logging out of the host : 
```
Traceback (most recent call last):
  File "/home/passhport/passhport/passhport/passhport", line 235, in <module>
    while not checkandconnect(indexed_target_list, choice, username, originalcmd):
  File "/home/passhport/passhport/passhport/passhport", line 94, in checkandconnect
    password.reset(target, login, sshoptions)
  File "/home/passhport/passhport/passhport/connections_utils/password.py", line 45, in reset
    elif useroption[1]:
IndexError: list index out of range
```

**Comment by elg** [comment]
to test

**Comment by Raphux** [comment]
Tested, works perfectly.
