### ISSUE TITLE
stacktrace when using "passhport-admin target delete" in interactive mode

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#250]
I have the following targets : 
```
root@passhport-dev-debian9:~# passhport-admin target list
firewall1.compagny.com
firewall2.compagny.com
websrv.ext.client.com
root@passhport-dev-debian9:~#
```
If I want to remove firewall1.compagny.com , in the interactive mode, a stacktrace is displayed : 
```
root@passhport-dev-debian9:~# passhport-admin target delete
Name: firewall1.compagny.com
Name: firewall1.compagny.com
Hostname: 87.65.43.219
Server Type : ssh
Login: root
Port: 22
SSH options: 
Comment: 
Attached users: 
Usergroup list: 
Users who can access this target: 
All usergroups: 
Member of the following targetgroups: 
Are you sure you want to delete firewall1.compagny.com? [y/N] y
Traceback (most recent call last):
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 488, in <module>
    requests_object_method(options)
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 475, in requests_object_method
    getattr(prompt_functions, method)(obj)
  File "/home/passhport/passhport/passhport-admin/manager/prompt_functions.py", line 52, in delete
    return req.get(req.url_passhport + obj + "/delete/" + name)
AttributeError: module 'manager.requests_functions' has no attribute 'url_passhport'
root@passhport-dev-debian9:~# 
```
But if I don't use the interactive mode, everything goes smoothly : 
```
root@passhport-dev-debian9:~# passhport-admin target delete firewall1.compagny.com
Name: firewall1.compagny.com
Hostname: 87.65.43.219
Server Type : ssh
Login: root
Port: 22
SSH options: 
Comment: 
Attached users: 
Usergroup list: 
Users who can access this target: 
All usergroups: 
Member of the following targetgroups: 
Are you sure you want to delete firewall1.compagny.com? [y/N] y
OK: "firewall1.compagny.com" -> deleted
root@passhport-dev-debian9:~# 
```

**Comment by Raphux** [comment]
Same for targetgroup : 
```
passhport@passhport-dev-debian9:~$ passhport-admin targetgroup delete
Name: network-appliances
Name: network-appliances
Comment: Network appliance group.
User list: 
Target list: 
Usergroup list: 
Targetgroup list: 
All users: 
All targets: 
All usergroups: 
All targetgroups: 
Are you sure you want to delete network-appliances? [y/N] y
Traceback (most recent call last):
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 488, in <module>
    requests_object_method(options)
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 475, in requests_object_method
    getattr(prompt_functions, method)(obj)
  File "/home/passhport/passhport/passhport-admin/manager/prompt_functions.py", line 52, in delete
    return req.get(req.url_passhport + obj + "/delete/" + name)
AttributeError: module 'manager.requests_functions' has no attribute 'url_passhport'
passhport@passhport-dev-debian9:~$ 
```

And usergroup : 
```
passhport@passhport-dev-debian9:~$ passhport-admin usergroup delete
Name: linux-admins
Name: linux-admins
Comment: 
User list: john@compagny.com
Usergroup list: 
All users: john@compagny.com
All usergroups: 
Are you sure you want to delete linux-admins? [y/N] y
Traceback (most recent call last):
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 488, in <module>
    requests_object_method(options)
  File "/home/passhport/passhport/passhport-admin/passhport-admin", line 475, in requests_object_method
    getattr(prompt_functions, method)(obj)
  File "/home/passhport/passhport/passhport-admin/manager/prompt_functions.py", line 52, in delete
    return req.get(req.url_passhport + obj + "/delete/" + name)
AttributeError: module 'manager.requests_functions' has no attribute 'url_passhport'
passhport@passhport-dev-debian9:~$
```

**Comment by elg** [comment]
Done.
