### ISSUE TITLE
Creating year log directory

### ISSUE THREAD

**Issue by elg** [LibrIT/passhport#355]
In 2019 the root directory of the logs is not automatically created leading to this kind of errors: 

Connecting to: passhport...

Traceback (most recent call last):

  File "/home/passhport/passhport/passhport/passhport", line 358, in <module>

    direct_connection(username, url_passhport, target_list, originalcmd)

  File "/home/passhport/passhport/passhport/passhport", line 226, in direct_connection

    ssh_direct_command(username, url_passhport, target_list, originalcmd)

  File "/home/passhport/passhport/passhport/passhport", line 243, in ssh_direct_command

    "")

  File "/home/passhport/passhport/passhport/passhport", line 121, in checkandconnect

    os.makedirs(pathlog)

  File "/home/passhport/passhport-run-env/lib64/python3.4/os.py", line 227, in makedirs

    makedirs(head, mode, exist_ok)

  File "/home/passhport/passhport-run-env/lib64/python3.4/os.py", line 227, in makedirs

    makedirs(head, mode, exist_ok)

  File "/home/passhport/passhport-run-env/lib64/python3.4/os.py", line 237, in makedirs

    mkdir(name, mode)

PermissionError: [Errno 13] Permission denied: '/var/log/passhport/2019'

**Comment by elg** [comment]
Certainly a rights issue on the /var/log/passhport directory.
The command is supposed to create the 2019 directory at the same time that the subdirectories... No special action to do for the year one.

Can't reproduce it (the directory was created correctly on my installations.
