### ISSUE TITLE
PaSSHport won't run with fresh install (problem with configparser)

### ISSUE THREAD

**Issue by Raphux** [LibrIT/passhport#370]
There is an issue with new fresh installs : passhportd won't start, because it complains about configparser : 
```
[passhport@localhost ~]$ /home/passhport/passhport-run-env/bin/python /home/passhport/passhport/passhportd/passhportd
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on https://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "/home/passhport/passhport/passhportd/passhportd", line 9, in <module>
    from config import SQLALCHEMY_DATABASE_DIR
  File "/home/passhport/passhport/passhportd/config.py", line 9, in <module>
    import os, sys, configparser
ImportError: No module named configparser
[passhport@localhost ~]$
```

**Comment by Raphux** [comment]
JFI : The issue impacts both Debian and CentOS.

**Comment by elg** [comment]
Workaround for python #371 commited.
Not a definitive solution but the problem should be solved on standard installations.

**Comment by elg** [comment]
I decrease the criticity

**Comment by elg** [comment]
workaround seems fine.
